version: 0.2

env:
  variables:
    LANDING_PATH: "$CODEBUILD_SRC_DIR/template_6"

phases:
  install:
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --storage-driver=overlay2 & 
      - sleep 30
      - docker info
  build:
    commands:
      - echo "Listing the contents of CODEBUILD_SRC_DIR:"
      - ls -al $CODEBUILD_SRC_DIR
      - echo "Building the Docker image..."
      - cd template_6
      - docker build -t 254492899594.dkr.ecr.us-east-1.amazonaws.com/ezrababait-landing:latest .
  post_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - $(aws ecr get-login --region us-east-1 --no-include-email)
      - echo "Pushing the Docker image..."
      - docker push 254492899594.dkr.ecr.us-east-1.amazonaws.com/ezrababait-landing:latest
      - echo "Docker image pushed successfully!"
